metadata.format.version = "1.1"

[versions]

minecraft = "1.21.10"
loader = "0.17.3"
api = "0.135.0" #Dont include the minecraft version
brigadier = "1.2.9"
parchment_mappings="2025.10.12"
neo="21.9.16-beta"
neoform="20251010.172816" #Dont include the minecraft version
mixin="0.8.5"
extras="0.5.0"

onnxruntime="1.19.0"
tokenizers="0.25.0"
configurate="4.2.0"
skript="2.12.1"
option="1.1.0"
checkerQual="3.51.1"
geantyref = "1.3.16"
djl = "0.34.0"

shadow-gradle-plugin="9.1.0"
paperweight-userdev="2.0.0-beta.18"
moddev-gradle="2.0.115"
fabric-loom="1.11-SNAPSHOT"
minotaur="2.8.10"
curseforge="1.1.26"
hangar="0.1.3"
github-release="2.5.2"


[libraries]

minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "loader" }
fabric_api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "api" }
brigadier = { group = "com.mojang", name = "brigadier", version.ref = "brigadier" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
extras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "extras" }

onnxruntime = { group = "com.microsoft.onnxruntime", name = "onnxruntime", version.ref = "onnxruntime" }
tokenizers = { group = "ai.djl.huggingface", name = "tokenizers", version.ref = "tokenizers" }
configurate_core = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
configurate_hocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
skript = { group = "com.github.SkriptLang", name = "Skript", version.ref = "skript" }
option = {group = "net.kyori", name = "option", version.ref = "option"}
checkerQual = { module = "org.checkerframework:checker-qual", version.ref = "checkerQual" }
geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }
djl_api = { module = "ai.djl:api", version.ref = "djl" }

# Build Stuff
shadow-gradle-plugin = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow-gradle-plugin" }
paperweight-userdev = { group = "io.papermc.paperweight", name = "paperweight-userdev", version.ref = "paperweight-userdev" }
moddev-gradle = { group = "net.neoforged", name = "moddev-gradle", version.ref = "moddev-gradle" }
fabric-loom = { group = "fabric-loom", name = "fabric-loom.gradle.plugin", version.ref = "fabric-loom" }
minotaur = { group = "com.modrinth.minotaur", name = "Minotaur", version.ref = "minotaur" }
curseforge = { group = "net.darkhax.curseforgegradle", name = "net.darkhax.curseforgegradle.gradle.plugin", version.ref = "curseforge" }
hangar = { group = "io.papermc.hangar-publish-plugin", name = "io.papermc.hangar-publish-plugin.gradle.plugin", version.ref = "hangar" }
github-release = { group = "com.github.breadmoirai", name = "github-release", version.ref = "github-release" }

[bundles]
build = [
    "shadow-gradle-plugin",
    "paperweight-userdev",
    "moddev-gradle",
    "fabric-loom",
    "minotaur",
    "curseforge",
    "hangar",
    "github-release"
]